version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: allThings-RealMadrid
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command:
      -url=jdbc:postgresql://db/allThings-RealMadrid -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
  api:
    profiles: ["dev"]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    volumes:
      - ./server:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/allThings-RealMadrid?schema=public"
volumes:
  db:
